package edu.umass.cs.iesl.watr
package native
package fabric

import scala.scalajs.js
import js.annotation.JSName



@js.native
trait ObjectProperties extends js.Object {
  @JSName("type")
  var otype:                     String = js.native // 'object',
  var originX:                  String = js.native // 'left',
  var originY:                  String = js.native // 'top',
  var top:                      Number = js.native // 0,
  var left:                     Number = js.native // 0,
  var width:                    Number = js.native // 0,
  var height:                   Number = js.native // 0,
  var scaleX:                   Number = js.native // 1,
  var scaleY:                   Number = js.native // 1,
  var flipX:                    Boolean = js.native // false,
  var flipY:                    Boolean = js.native // false,
  var opacity:                  Number = js.native // 1,
  var angle:                    Number = js.native // 0,
  var skewX:                    Number = js.native // 0,
  var skewY:                    Number = js.native // 0,
  var cornerSize:               Number = js.native // 13,
  var transparentCorners:       Boolean = js.native // true,
  var hoverCursor:              String = js.native // null,
  var moveCursor:               String = js.native // null,
  var padding:                  Number = js.native // 0,
  var borderColor:              String = js.native // 'rgba(102,153,255,0.75)',
  var borderDashArray:          js.Array[String] = js.native // null,
  var cornerColor:              String = js.native // 'rgba(102,153,255,0.5)',
  var cornerStrokeColor:        String = js.native // null,
  var cornerStyle:          String = js.native // 'rect',
  var cornerDashArray:          js.Array[String] = js.native // null,
  var centeredScaling:          Boolean = js.native // false,
  var centeredRotation:         Boolean = js.native // true,
  var fill:                     String = js.native // 'rgb(0,0,0)',
  var fillRule:                 String = js.native // 'nonzero',
  var globalCompositeOperation: String = js.native // 'source-over',
  var backgroundColor:          String = js.native // '',
  var selectionBackgroundColor:          String = js.native // '',
  var stroke:                   String = js.native // null,
  var strokeWidth:              Number = js.native // 1,
  var strokeDashArray:          js.Array[String] = js.native // null,
  var strokeLineCap:            String = js.native // 'butt',
  var strokeLineJoin:           String = js.native // 'miter',
  var strokeMiterLimit:         Number = js.native // 10,
  // var shadow:                   Shadow = js.native // null,
  var borderOpacityWhenMoving:  Number = js.native // 0.4,
  var borderScaleFactor:        Number = js.native // 1,
  // var transformMatrix:          Array = js.native // null,
  var minScaleLimit:            Number = js.native // 0.01,
  var selectable:               Boolean = js.native // true,
  var evented:                  Boolean = js.native // true,
  var visible:                  Boolean = js.native // true,
  var hasControls:              Boolean = js.native // true,
  var hasBorders:               Boolean = js.native // true,
  var hasRotatingPoint:         Boolean = js.native // true,
  var rotatingPointOffset:      Number = js.native // 40,
  var perPixelTargetFind:       Boolean = js.native // false,
  var includeDefaultValues:     Boolean = js.native // true,
  var clipTo:                   js.Function = js.native // null,
  var lockMovementX:            Boolean = js.native // false,
  var lockMovementY:            Boolean = js.native // false,
  var lockRotation:             Boolean = js.native // false,
  var lockScalingX:             Boolean = js.native // false,
  var lockScalingY:             Boolean = js.native // false,
  var lockUniScaling:           Boolean = js.native // false,
  var lockSkewingX:             Boolean = js.native // false,
  var lockSkewingY:             Boolean = js.native // false,
  var lockScalingFlip:          Boolean = js.native // false,
  var excludeFromExport:          Boolean = js.native // false,
}
