
* Tracelog File Description

** File Format overview
   The format of the tracelog.json file is a list of entries, where each entry
   is either a geometric figure, or a relation.

   Geometric figures can be rectangles, lines, trapezoids, or points. Each
   figure has an id number and one or more associated labels.

   Entries also have a set of headers, which include the time at which the entry
   was created, and some additional tags, and a "name" field. The name field is
   the only one that is useful when parsing the log entries, as it identifies
   the type of a Relation entry, which is described below.


** Tracelog Entry Examples 

*** Geometry Example 1
    This is a Geometry entry for the rectange describing the position of a line of text (baseline-midrise bounds):

    #+BEGIN_SRC js
        {                                                  //
             "page": 0,                                    // + page# on which this shape appears
             "logType": "Geometry",                        // + logType is either "Geometry" or "Relation"
             "body": [                                     // + For logType="Geometry", body consists of a list of labeled shapes with id numbers
               {                                           //
                 "labels": "BaselineMidriseBand",          //
                 "id": 22954,                              // + Ids are unique within a single tracelog.json file, and used to specify relationships between shapes
                 "LTBounds": [31738, 45517, 22710, 486]    // + Geometric figures can be rectangles (LTBounds), Trapezoids, Points, Lines
               }                                           //
             ],                                            //
             "headers": {                                  // + Headers provide additional tags and timing info, which are used by the
               "timestamp": 1537553329967,                 //   web UI for display.
               "tags": "BaselineMidriseBand",              //
               "callSite": "findLineCharsInPageBand",      //
               "name": ""                                  // + For Relations, "name" is used to specify the type of relation
             }                                             //
        }                                                  //
    #+END_SRC

*** Geometry Example 2
    Another Geometry entry for the Trapezoid created by consecutive text baselines:

    #+BEGIN_SRC js
        {                                                     //
           "page": 11,                                        //
           "logType": "Geometry",                             //
           "body": [                                          //
             {                                                //
               "labels": "LinePairTrapezoid",                 //
               "id": 4127,                                    //
               "Trapezoid": {                                 //  + Trapezoids are specified by top-left, bottom-left points plus top/bottom widths (thus only
                 "bottomWidth": 7228,                         //    allowing trapezoids with horizontal top and bottom lines)
                 "bottomLeft": { "y": 29508, "x": 32899 },    //
                 "topWidth": 23973,                           //
                 "topLeft": { "y": 28516, "x": 31364 }        //
               }                                              //
             }                                                //
           ],                                                 //
           "headers": {                                       //
             "timestamp": 1537553332400,                      //
             "tags": "LinePairTrapezoid",                     //
             "callSite": "buildLinePairTrapezoids",           //
             "name": ""                                       //
           }                                                  //
         }                                                    //

    #+END_SRC


*** Relation example 1
    A Relation between a Trapezoid and its upper and lower text line shapes (the BaselineMidriseBand)


    #+BEGIN_SRC js
         {                                                //
           "page": 11,                                    //
           "logType": "Relation",                         //
           "body": [                                      // + The body is a list three shape IDs
             4127,                                        //
             3973,                                        //
             3976                                         //
           ],                                             //
           "fieldTypes": [                                // + The labels for each of the items in the relation
             "LinePairTrapezoid",                         //
             "BaselineMidriseBand",                       //
             "BaselineMidriseBand"                        //
           ],                                             //
           "headers": {                                   //
             "timestamp": 1537553332400,                  //
             "tags": "",                                  //
             "callSite": "buildLinePairTrapezoids",       //
             "name": "TrapezoidLinePairs"                 // + Name of this type of relation
           }                                              //
         }                                                //

    #+END_SRC


*** Relation example 2 (font linking)
    A Relation specifying the fonts that occur in a line of text, specified as a list of font names plus (begin, length) ranges.
    Font descriptions are contained in a separate file, and described in the [[./FontSummaryDescription.org][Font Summary Description Document]].

    #+BEGIN_SRC js
         {                                              //
            "page": 1,                                  //
            "logType": "Relation",                      //
            "body": [                                   // + Body
              8083,                                     // + ID for BaselineMidriseBand shape
              [                                         // + List of fonts with character ranges
                ["MOOKAP+AdvPSTimx99", 0, 15],          //   e.g., [FontName, Begin, Length],
                ["MOOOEH+AdvP4C4E74x99", 15, 1],        //         ...
                ["MOOKAP+AdvPSTimx99", 16, 25],         //
                ["MOOOEH+AdvP4C4E74x99", 41, 1],        //
                ["MOOKAP+AdvPSTimx99", 42, 4]           //
              ]                                         //
            ],                                          //
            "fieldTypes": [                             //
              "BaselineMidriseBand",                    //
              "FontRanges"                              //
            ],                                          //
            "headers": {                                //
              "timestamp": 1537553330079,               //
              "tags": "",                               //
              "callSite": "findLineCharsInPageBand",    //
              "name": "TextLineFontRanges"              // + Name of this type of relation
            }                                           //
          }                                             //

    #+END_SRC
