package edu.umass.cs.iesl.watr
package simstring

import heuristics.Constants._

object CityKeywords {

    final val keywords = FuzzyMap(List(("6th of october city", CITY_KEYWORD),
        ("aabenraa", CITY_KEYWORD),
        ("aachen", CITY_KEYWORD),
        ("aalborg", CITY_KEYWORD),
        ("aalen", CITY_KEYWORD),
        ("aalst", CITY_KEYWORD),
        ("aalto", CITY_KEYWORD),
        ("aarau", CITY_KEYWORD),
        ("aarhus", CITY_KEYWORD),
        ("aas", CITY_KEYWORD),
        ("aba", CITY_KEYWORD),
        ("abakaliki", CITY_KEYWORD),
        ("abashiri", CITY_KEYWORD),
        ("abbeville", CITY_KEYWORD),
        ("abbotsford", CITY_KEYWORD),
        ("abbottabad", CITY_KEYWORD),
        ("abeokuta", CITY_KEYWORD),
        ("aberdare", CITY_KEYWORD),
        ("aberdeen", CITY_KEYWORD),
        ("aberdeen proving ground", CITY_KEYWORD),
        ("abergavenny", CITY_KEYWORD),
        ("aberystwyth", CITY_KEYWORD),
        ("abha", CITY_KEYWORD),
        ("abhipur", CITY_KEYWORD),
        ("abidjan", CITY_KEYWORD),
        ("abiko", CITY_KEYWORD),
        ("abilene", CITY_KEYWORD),
        ("abingdon", CITY_KEYWORD),
        ("abington", CITY_KEYWORD),
        ("abo", CITY_KEYWORD),
        ("abraka", CITY_KEYWORD),
        ("absecon", CITY_KEYWORD),
        ("abu dhabi", CITY_KEYWORD),
        ("abuja", CITY_KEYWORD),
        ("acapulco", CITY_KEYWORD),
        ("accord", CITY_KEYWORD),
        ("accra", CITY_KEYWORD),
        ("accrington", CITY_KEYWORD),
        ("ackley", CITY_KEYWORD),
        ("a coruna", CITY_KEYWORD),
        ("a coruña", CITY_KEYWORD),
        ("acton", CITY_KEYWORD),
        ("acworth", CITY_KEYWORD),
        ("ada", CITY_KEYWORD),
        ("adachi-ku", CITY_KEYWORD),
        ("adair", CITY_KEYWORD),
        ("adama", CITY_KEYWORD),
        ("adams", CITY_KEYWORD),
        ("adamstown", CITY_KEYWORD),
        ("adamsville", CITY_KEYWORD),
        ("adana", CITY_KEYWORD),
        ("addis ababa", CITY_KEYWORD),
        ("addison", CITY_KEYWORD),
        ("addlestone", CITY_KEYWORD),
        ("adel", CITY_KEYWORD),
        ("adelaide", CITY_KEYWORD),
        ("adelanto", CITY_KEYWORD),
        ("adelphi", CITY_KEYWORD),
        ("aden", CITY_KEYWORD),
        ("ado ekiti", CITY_KEYWORD),
        ("adoor", CITY_KEYWORD),
        ("adrian", CITY_KEYWORD),
        ("adrigrat", CITY_KEYWORD),
        ("advance", CITY_KEYWORD),
        ("affoltern am albis", CITY_KEYWORD),
        ("afton", CITY_KEYWORD),
        ("afyon", CITY_KEYWORD),
        ("agartala", CITY_KEYWORD),
        ("agawam", CITY_KEYWORD),
        ("agen", CITY_KEYWORD),
        ("ageo", CITY_KEYWORD),
        ("ago iwoye", CITY_KEYWORD),
        ("agoura hills", CITY_KEYWORD),
        ("agra", CITY_KEYWORD),
        ("agrate brianza", CITY_KEYWORD),
        ("aguadilla", CITY_KEYWORD),
        ("aguascalientes", CITY_KEYWORD),
        ("ahmedabad", CITY_KEYWORD),
        ("ahmednagar", CITY_KEYWORD),
        ("ahoskie", CITY_KEYWORD),
        ("ahvaz", CITY_KEYWORD),
        ("ahwaz", CITY_KEYWORD),
        ("aichi-gun", CITY_KEYWORD),
        ("aiea", CITY_KEYWORD),
        ("aiken", CITY_KEYWORD),
        ("ainsworth", CITY_KEYWORD),
        ("airdrie", CITY_KEYWORD),
        ("aitkenvale", CITY_KEYWORD),
        ("aitkin", CITY_KEYWORD),
        ("aix en provence", CITY_KEYWORD),
        ("aix-en-provence", CITY_KEYWORD),
        ("aizawl", CITY_KEYWORD),
        ("aizuwakamatsu", CITY_KEYWORD),
        ("aizwal", CITY_KEYWORD),
        ("ajax", CITY_KEYWORD),
        ("ajman", CITY_KEYWORD),
        ("ajmer", CITY_KEYWORD),
        ("akashi", CITY_KEYWORD),
        ("akersberga", CITY_KEYWORD),
        ("aki-gun", CITY_KEYWORD),
        ("akishima", CITY_KEYWORD),
        ("akita", CITY_KEYWORD),
        ("ako", CITY_KEYWORD),
        ("akoka yaba", CITY_KEYWORD),
        ("akola", CITY_KEYWORD),
        ("akron", CITY_KEYWORD),
        ("aksu", CITY_KEYWORD),
        ("aktobe", CITY_KEYWORD),
        ("akure", CITY_KEYWORD),
        ("akureyri", CITY_KEYWORD),
        ("akwesasne", CITY_KEYWORD),
        ("alabaster", CITY_KEYWORD),
        ("alacant", CITY_KEYWORD),
        ("alachua", CITY_KEYWORD),
        ("al ain", CITY_KEYWORD),
        ("al-ain", CITY_KEYWORD),
        ("alajuela", CITY_KEYWORD),
        ("alameda", CITY_KEYWORD),
        ("alamo", CITY_KEYWORD),
        ("alamogordo", CITY_KEYWORD),
        ("alamosa", CITY_KEYWORD),
        ("alappuzha", CITY_KEYWORD),
        ("alashankou", CITY_KEYWORD),
        ("alba", CITY_KEYWORD),
        ("albacete", CITY_KEYWORD),
        ("al baha", CITY_KEYWORD),
        ("albany", CITY_KEYWORD),
        ("albany creek", CITY_KEYWORD),
        ("albemarle", CITY_KEYWORD),
        ("albert lea", CITY_KEYWORD),
        ("alberton", CITY_KEYWORD),
        ("albert park", CITY_KEYWORD),
        ("albertslund", CITY_KEYWORD),
        ("albertson", CITY_KEYWORD),
        ("albertville", CITY_KEYWORD),
        ("albi", CITY_KEYWORD),
        ("albion", CITY_KEYWORD),
        ("alborg", CITY_KEYWORD),
        ("albuquerque", CITY_KEYWORD),
        ("albury", CITY_KEYWORD),
        ("alcala de henares", CITY_KEYWORD),
        ("alcalá de henares", CITY_KEYWORD),
        ("alcester", CITY_KEYWORD),
        ("alcoa", CITY_KEYWORD),
        ("alcobendas", CITY_KEYWORD),
        ("alcorcon", CITY_KEYWORD),
        ("alcorcón", CITY_KEYWORD),
        ("alden", CITY_KEYWORD),
        ("aldershot", CITY_KEYWORD),
        ("aledo", CITY_KEYWORD),
        ("alencon", CITY_KEYWORD),
        ("aleppo", CITY_KEYWORD),
        ("alessandria", CITY_KEYWORD),
        ("alesund", CITY_KEYWORD),
        ("alexander", CITY_KEYWORD),
        ("alexander city", CITY_KEYWORD),
        ("alexandra", CITY_KEYWORD),
        ("alexandria", CITY_KEYWORD),
        ("alexandria bay", CITY_KEYWORD),
        ("alfred", CITY_KEYWORD),
        ("alfreton", CITY_KEYWORD),
        ("alger", CITY_KEYWORD),
        ("alges", CITY_KEYWORD),
        ("algés", CITY_KEYWORD),
        ("algiers", CITY_KEYWORD),
        ("algona", CITY_KEYWORD),
        ("algonquin", CITY_KEYWORD),
        ("alhambra", CITY_KEYWORD),
        ("al-hasa", CITY_KEYWORD),
        ("alicante", CITY_KEYWORD),
        ("alice", CITY_KEYWORD),
        ("alice springs", CITY_KEYWORD),
        ("aligarh", CITY_KEYWORD),
        ("aliquippa", CITY_KEYWORD),
        ("aliso viejo", CITY_KEYWORD),
        ("al-kharj", CITY_KEYWORD),
        ("al khobar", CITY_KEYWORD),
        ("al-khobar", CITY_KEYWORD),
        ("alkmaar", CITY_KEYWORD),
        ("allahabad", CITY_KEYWORD),
        ("allegan", CITY_KEYWORD),
        ("allegany", CITY_KEYWORD),
        ("allen", CITY_KEYWORD),
        ("allendale", CITY_KEYWORD),
        ("allen park", CITY_KEYWORD),
        ("allentown", CITY_KEYWORD),
        ("allerod", CITY_KEYWORD),
        ("alliance", CITY_KEYWORD),
        ("allison park", CITY_KEYWORD),
        ("alliston", CITY_KEYWORD),
        ("alloa", CITY_KEYWORD),
        ("allschwil", CITY_KEYWORD),
        ("allston", CITY_KEYWORD),
        ("alma", CITY_KEYWORD),
        ("almada", CITY_KEYWORD),
        ("almaty", CITY_KEYWORD),
        ("almelo", CITY_KEYWORD),
        ("almere", CITY_KEYWORD),
        ("almeria", CITY_KEYWORD),
        ("almería", CITY_KEYWORD),
        ("al minia", CITY_KEYWORD),
        ("almond", CITY_KEYWORD),
        ("almont", CITY_KEYWORD),
        ("almonte", CITY_KEYWORD),
        ("alnarp", CITY_KEYWORD),
        ("aloha", CITY_KEYWORD),
        ("alor setar", CITY_KEYWORD),
        ("alpena", CITY_KEYWORD),
        ("alpha", CITY_KEYWORD),
        ("alpharetta", CITY_KEYWORD),
        ("alphen aan den rijn", CITY_KEYWORD),
        ("alphington", CITY_KEYWORD),
        ("alpine", CITY_KEYWORD),
        ("al-salt", CITY_KEYWORD),
        ("alsip", CITY_KEYWORD),
        ("alta", CITY_KEYWORD),
        ("altadena", CITY_KEYWORD),
        ("altamira", CITY_KEYWORD),
        ("altamont", CITY_KEYWORD),
        ("altamonte springs", CITY_KEYWORD),
        ("altay", CITY_KEYWORD),
        ("altdorf", CITY_KEYWORD),
        ("altenburg", CITY_KEYWORD),
        ("alto", CITY_KEYWORD),
        ("alton", CITY_KEYWORD),
        ("altona", CITY_KEYWORD),
        ("altoona", CITY_KEYWORD),
        ("altrincham", CITY_KEYWORD),
        ("alturas", CITY_KEYWORD),
        ("altus", CITY_KEYWORD),
        ("altus afb", CITY_KEYWORD),
        ("aluva", CITY_KEYWORD),
        ("alva", CITY_KEYWORD),
        ("alvarado", CITY_KEYWORD),
        ("alvaro obregon", CITY_KEYWORD),
        ("älvaro obregón", CITY_KEYWORD),
        ("alvin", CITY_KEYWORD),
        ("alwar", CITY_KEYWORD),
        ("alytus", CITY_KEYWORD),
        ("alzenau", CITY_KEYWORD),
        ("amadora", CITY_KEYWORD),
        ("amagasaki", CITY_KEYWORD),
        ("amanda", CITY_KEYWORD),
        ("amarillo", CITY_KEYWORD),
        ("ambala", CITY_KEYWORD),
        ("ambala cantt", CITY_KEYWORD),
        ("amberg", CITY_KEYWORD),
        ("ambernath", CITY_KEYWORD),
        ("ambler", CITY_KEYWORD),
        ("ambo", CITY_KEYWORD),
        ("ambon", CITY_KEYWORD),
        ("ambridge", CITY_KEYWORD),
        ("amelia", CITY_KEYWORD),
        ("amenia", CITY_KEYWORD),
        ("american falls", CITY_KEYWORD),
        ("american fork", CITY_KEYWORD),
        ("americus", CITY_KEYWORD),
        ("amersfoort", CITY_KEYWORD),
        ("amersham", CITY_KEYWORD),
        ("ames", CITY_KEYWORD),
        ("amesbury", CITY_KEYWORD),
        ("amherst", CITY_KEYWORD),
        ("amiens", CITY_KEYWORD),
        ("amity", CITY_KEYWORD),
        ("amityville", CITY_KEYWORD),
        ("amman", CITY_KEYWORD),
        ("ammanford", CITY_KEYWORD),
        ("ammon", CITY_KEYWORD),
        ("amravati", CITY_KEYWORD),
        ("amritsar", CITY_KEYWORD),
        ("amstelveen", CITY_KEYWORD),
        ("amsterdam", CITY_KEYWORD),
        ("anaconda", CITY_KEYWORD),
        ("anacortes", CITY_KEYWORD),
        ("anadarko", CITY_KEYWORD),
        ("anaheim", CITY_KEYWORD),
        ("anahuac", CITY_KEYWORD),
        ("anamosa", CITY_KEYWORD),
        ("anand", CITY_KEYWORD),
        ("anantapur", CITY_KEYWORD),
        ("anapolis", CITY_KEYWORD),
        ("anápolis", CITY_KEYWORD),
        ("ancaster", CITY_KEYWORD),
        ("anchorage", CITY_KEYWORD),
        ("ancona", CITY_KEYWORD),
        ("anda", CITY_KEYWORD),
        ("andalusia", CITY_KEYWORD),
        ("andernach", CITY_KEYWORD),
        ("anderson", CITY_KEYWORD),
        ("andijan", CITY_KEYWORD),
        ("andong", CITY_KEYWORD),
        ("andorra la vella", CITY_KEYWORD),
        ("andover", CITY_KEYWORD),
        ("andrews", CITY_KEYWORD),
        ("andrews afb", CITY_KEYWORD),
        ("angamaly", CITY_KEYWORD),
        ("angaston", CITY_KEYWORD),
        ("angelholm", CITY_KEYWORD),
        ("angels camp", CITY_KEYWORD),
        ("angers", CITY_KEYWORD),
        ("angier", CITY_KEYWORD),
        ("angleton", CITY_KEYWORD),
        ("angola", CITY_KEYWORD),
        ("angouleme", CITY_KEYWORD),
        ("anguo", CITY_KEYWORD),
        ("angus", CITY_KEYWORD),
        ("angwin", CITY_KEYWORD),
        ("anita", CITY_KEYWORD),
        ("anjo", CITY_KEYWORD),
        ("ankang", CITY_KEYWORD),
        ("ankara", CITY_KEYWORD),
        ("ankeny", CITY_KEYWORD),
        ("ankleshwar", CITY_KEYWORD),
        ("anlu", CITY_KEYWORD),
        ("anna", CITY_KEYWORD),
        ("annaba", CITY_KEYWORD),
        ("annamalai nagar", CITY_KEYWORD),
        ("annan", CITY_KEYWORD),
        ("annandale", CITY_KEYWORD),
        ("annandale-on-hudson", CITY_KEYWORD),
        ("annapolis", CITY_KEYWORD),
        ("ann arbor", CITY_KEYWORD),
        ("annecy", CITY_KEYWORD),
        ("annerley", CITY_KEYWORD),
        ("anning", CITY_KEYWORD),
        ("anniston", CITY_KEYWORD),
        ("annville", CITY_KEYWORD),
        ("anoka", CITY_KEYWORD),
        ("anqing", CITY_KEYWORD),
        ("anqiu", CITY_KEYWORD),
        ("ansan", CITY_KEYWORD),
        ("ansbach", CITY_KEYWORD),
        ("anseong", CITY_KEYWORD),
        ("anshan", CITY_KEYWORD),
        ("anshun", CITY_KEYWORD),
        ("anson", CITY_KEYWORD),
        ("ansonia", CITY_KEYWORD),
        ("antalya", CITY_KEYWORD),
        ("antananarivo", CITY_KEYWORD),
        ("antelope", CITY_KEYWORD),
        ("anthem", CITY_KEYWORD),
        ("anthony", CITY_KEYWORD),
        ("antigo", CITY_KEYWORD),
        ("antigonish", CITY_KEYWORD),
        ("antioch", CITY_KEYWORD),
        ("antofagasta", CITY_KEYWORD),
        ("antony", CITY_KEYWORD),
        ("antrim", CITY_KEYWORD),
        ("antwerp", CITY_KEYWORD),
        ("antwerpen", CITY_KEYWORD),
        ("anwai", CITY_KEYWORD),
        ("anyang", CITY_KEYWORD),
        ("anyigba", CITY_KEYWORD),
        ("aomori", CITY_KEYWORD),
        ("aosta", CITY_KEYWORD),
        ("apache", CITY_KEYWORD),
        ("apache junction", CITY_KEYWORD),
        ("apapa", CITY_KEYWORD),
        ("apatity", CITY_KEYWORD),
        ("apeldoorn", CITY_KEYWORD),
        ("apex", CITY_KEYWORD),
        ("apia", CITY_KEYWORD),
        ("apodaca", CITY_KEYWORD),
        ("apopka", CITY_KEYWORD),
        ("applecross", CITY_KEYWORD),
        ("appleton", CITY_KEYWORD),
        ("appleton city", CITY_KEYWORD),
        ("apple valley", CITY_KEYWORD),
        ("appomattox", CITY_KEYWORD),
        ("aptos", CITY_KEYWORD),
        ("arab", CITY_KEYWORD),
        ("aracaju", CITY_KEYWORD),
        ("aracatuba", CITY_KEYWORD),
        ("arak", CITY_KEYWORD),
        ("arakawa-ku", CITY_KEYWORD),
        ("arakkunnam", CITY_KEYWORD),
        ("aral", CITY_KEYWORD),
        ("aransas pass", CITY_KEYWORD),
        ("arapahoe", CITY_KEYWORD),
        ("arar", CITY_KEYWORD),
        ("araraquara", CITY_KEYWORD),
        ("arau", CITY_KEYWORD),
        ("arcadia", CITY_KEYWORD),
        ("arcanum", CITY_KEYWORD),
        ("arcata", CITY_KEYWORD),
        ("arcavacata di rende", CITY_KEYWORD),
        ("archbald", CITY_KEYWORD),
        ("archbold", CITY_KEYWORD),
        ("arco", CITY_KEYWORD),
        ("arcueil", CITY_KEYWORD),
        ("arden", CITY_KEYWORD),
        ("ardmore", CITY_KEYWORD),
        ("ardrossan", CITY_KEYWORD),
        ("ardsley", CITY_KEYWORD),
        ("arecibo", CITY_KEYWORD),
        ("arendal", CITY_KEYWORD),
        ("arequipa", CITY_KEYWORD),
        ("arezzo", CITY_KEYWORD),
        ("argyle", CITY_KEYWORD),
        ("arhus", CITY_KEYWORD),
        ("århus", CITY_KEYWORD),
        ("arkadelphia", CITY_KEYWORD),
        ("arkansas city", CITY_KEYWORD),
        ("arkhangelsk", CITY_KEYWORD),
        ("arles", CITY_KEYWORD),
        ("arlington", CITY_KEYWORD),
        ("arlington heights", CITY_KEYWORD),
        ("arlon", CITY_KEYWORD),
        ("arma", CITY_KEYWORD),
        ("armada", CITY_KEYWORD),
        ("armadale", CITY_KEYWORD),
        ("armagh", CITY_KEYWORD),
        ("armidale", CITY_KEYWORD),
        ("armonk", CITY_KEYWORD),
        ("armstrong", CITY_KEYWORD),
        ("arnhem", CITY_KEYWORD),
        ("arnold", CITY_KEYWORD),
        ("arnprior", CITY_KEYWORD),
        ("arras", CITY_KEYWORD),
        ("arroyo grande", CITY_KEYWORD),
        ("artarmon", CITY_KEYWORD),
        ("artesia", CITY_KEYWORD),
        ("arthur", CITY_KEYWORD),
        ("artux", CITY_KEYWORD),
        ("arua", CITY_KEYWORD),
        ("arusha", CITY_KEYWORD),
        ("arvada", CITY_KEYWORD),
        ("arxan", CITY_KEYWORD),
        ("asaba", CITY_KEYWORD),
        ("asahikawa", CITY_KEYWORD),
        ("asan", CITY_KEYWORD),
        ("asansol", CITY_KEYWORD),
        ("aschaffenburg", CITY_KEYWORD),
        ("ascot", CITY_KEYWORD),
        ("ashbourne", CITY_KEYWORD),
        ("ashburn", CITY_KEYWORD),
        ("ashburnham", CITY_KEYWORD),
        ("ashburton", CITY_KEYWORD),
        ("ashby", CITY_KEYWORD),
        ("ashby-de-la-zouch", CITY_KEYWORD),
        ("ashdod", CITY_KEYWORD),
        ("ashdown", CITY_KEYWORD),
        ("asheboro", CITY_KEYWORD),
        ("asheville", CITY_KEYWORD),
        ("ashfield", CITY_KEYWORD),
        ("ashford", CITY_KEYWORD),
        ("ashgabat", CITY_KEYWORD),
        ("ashgrove", CITY_KEYWORD),
        ("ashigarakami-gun", CITY_KEYWORD),
        ("ashikaga", CITY_KEYWORD),
        ("ashington", CITY_KEYWORD),
        ("ashiya", CITY_KEYWORD),
        ("ashland", CITY_KEYWORD),
        ("ashland city", CITY_KEYWORD),
        ("ashley", CITY_KEYWORD),
        ("ashmore", CITY_KEYWORD),
        ("ashtabula", CITY_KEYWORD),
        ("ashton", CITY_KEYWORD),
        ("ashton under lyne", CITY_KEYWORD),
        ("ashton-under-lyne", CITY_KEYWORD),
        ("ashville", CITY_KEYWORD),
        ("asker", CITY_KEYWORD),
        ("asmara", CITY_KEYWORD),
        ("asnieres", CITY_KEYWORD),
        ("aspen", CITY_KEYWORD),
        ("aspley", CITY_KEYWORD),
        ("assago", CITY_KEYWORD),
        ("assen", CITY_KEYWORD),
        ("assiut", CITY_KEYWORD),
        ("astana", CITY_KEYWORD),
        ("asti", CITY_KEYWORD),
        ("aston", CITY_KEYWORD),
        ("astoria", CITY_KEYWORD),
        ("asuncion", CITY_KEYWORD),
        ("asunción", CITY_KEYWORD),
        ("atascadero", CITY_KEYWORD),
        ("atchison", CITY_KEYWORD),
        ("atco", CITY_KEYWORD),
        ("atglen", CITY_KEYWORD),
        ("athabasca", CITY_KEYWORD),
        ("athena", CITY_KEYWORD),
        ("athens", CITY_KEYWORD),
        ("atherton", CITY_KEYWORD),
        ("athinon", CITY_KEYWORD),
        ("athlone", CITY_KEYWORD),
        ("athol", CITY_KEYWORD),
        ("atizapan de zaragoza", CITY_KEYWORD),
        ("atkinson", CITY_KEYWORD),
        ("atlanta", CITY_KEYWORD),
        ("atlantic", CITY_KEYWORD),
        ("atlantic city", CITY_KEYWORD),
        ("atmore", CITY_KEYWORD),
        ("atoka", CITY_KEYWORD),
        ("atsugi", CITY_KEYWORD),
        ("attalla", CITY_KEYWORD),
        ("attard", CITY_KEYWORD),
        ("attica", CITY_KEYWORD),
        ("attleboro", CITY_KEYWORD),
        ("atwater", CITY_KEYWORD),
        ("atwood", CITY_KEYWORD),
        ("atyrau", CITY_KEYWORD),
        ("aubagne", CITY_KEYWORD),
        ("aubervilliers", CITY_KEYWORD),
        ("aubiere", CITY_KEYWORD),
        ("aubière", CITY_KEYWORD),
        ("aubrey", CITY_KEYWORD),
        ("auburn", CITY_KEYWORD),
        ("auburndale", CITY_KEYWORD),
        ("auburn hills", CITY_KEYWORD),
        ("auchenflower", CITY_KEYWORD),
        ("auckland", CITY_KEYWORD),
        ("auckland park", CITY_KEYWORD),
        ("audubon", CITY_KEYWORD),
        ("augsburg", CITY_KEYWORD),
        ("augusta", CITY_KEYWORD),
        ("aulendorf", CITY_KEYWORD),
        ("aurangabad", CITY_KEYWORD),
        ("aurich", CITY_KEYWORD),
        ("aurora", CITY_KEYWORD),
        ("austell", CITY_KEYWORD),
        ("austin", CITY_KEYWORD),
        ("ava", CITY_KEYWORD),
        ("avalon", CITY_KEYWORD),
        ("aveiro", CITY_KEYWORD),
        ("avellino", CITY_KEYWORD),
        ("avenal", CITY_KEYWORD),
        ("avenel", CITY_KEYWORD),
        ("aventura", CITY_KEYWORD),
        ("averill park", CITY_KEYWORD),
        ("aversa", CITY_KEYWORD),
        ("avery", CITY_KEYWORD),
        ("avignon", CITY_KEYWORD),
        ("avila", CITY_KEYWORD),
        ("aviles", CITY_KEYWORD),
        ("avoca", CITY_KEYWORD),
        ("avon", CITY_KEYWORD),
        ("avondale", CITY_KEYWORD),
        ("avon lake", CITY_KEYWORD),
        ("avon park", CITY_KEYWORD),
        ("awka", CITY_KEYWORD),
        ("axtell", CITY_KEYWORD),
        ("ayabe", CITY_KEYWORD),
        ("ayase", CITY_KEYWORD),
        ("ayden", CITY_KEYWORD),
        ("ayer", CITY_KEYWORD),
        ("aylesbury", CITY_KEYWORD),
        ("aylesford", CITY_KEYWORD),
        ("ayr", CITY_KEYWORD),
        ("azamgarh", CITY_KEYWORD),
        ("azle", CITY_KEYWORD),
        ("azusa", CITY_KEYWORD),
        ("baar", CITY_KEYWORD),
        ("baarn", CITY_KEYWORD),
        ("babol", CITY_KEYWORD),
        ("babolsar", CITY_KEYWORD),
        ("babson park", CITY_KEYWORD),
        ("babylon", CITY_KEYWORD),
        ("bacchus marsh", CITY_KEYWORD),
        ("bacolod city", CITY_KEYWORD),
        ("badajoz", CITY_KEYWORD),
        ("badalona", CITY_KEYWORD),
        ("bad axe", CITY_KEYWORD),
        ("bad berleburg", CITY_KEYWORD),
        ("baddi", CITY_KEYWORD),
        ("baden", CITY_KEYWORD),
        ("baden-baden", CITY_KEYWORD),
        ("badhada", CITY_KEYWORD),
        ("bad homburg", CITY_KEYWORD),
        ("bad honnef", CITY_KEYWORD),
        ("bad kreuznach", CITY_KEYWORD),
        ("bad krozingen", CITY_KEYWORD),
        ("bad lippspringe", CITY_KEYWORD),
        ("bad nauheim", CITY_KEYWORD),
        ("bad neustadt/saale", CITY_KEYWORD),
        ("bad oeynhausen", CITY_KEYWORD),
        ("bad salzuflen", CITY_KEYWORD),
        ("bad soden", CITY_KEYWORD),
        ("bad tolz", CITY_KEYWORD),
        ("bad vilbel", CITY_KEYWORD),
        ("bad wildungen", CITY_KEYWORD),
        ("bagalkot", CITY_KEYWORD),
        ("baghdad", CITY_KEYWORD),
        ("bagley", CITY_KEYWORD),
        ("bagneux", CITY_KEYWORD),
        ("bagno a ripoli", CITY_KEYWORD),
        ("bagsvaerd", CITY_KEYWORD),
        ("baguio city", CITY_KEYWORD),
        ("bahadurgarh", CITY_KEYWORD),
        ("bahia blanca", CITY_KEYWORD),
        ("bahía blanca", CITY_KEYWORD),
        ("bahir dar", CITY_KEYWORD),
        ("baicheng", CITY_KEYWORD),
        ("baie-comeau", CITY_KEYWORD),
        ("baileyville", CITY_KEYWORD),
        ("bainbridge", CITY_KEYWORD),
        ("bainbridge island", CITY_KEYWORD),
        ("bairnsdale", CITY_KEYWORD),
        ("baise", CITY_KEYWORD),
        ("baishan", CITY_KEYWORD),
        ("baiyin", CITY_KEYWORD),
        ("baker", CITY_KEYWORD),
        ("baker city", CITY_KEYWORD),
        ("bakersfield", CITY_KEYWORD),
        ("baku", CITY_KEYWORD),
        ("bala cynwyd", CITY_KEYWORD),
        ("balaklava", CITY_KEYWORD),
        ("balasore", CITY_KEYWORD),
        ("baldwin", CITY_KEYWORD),
        ("baldwin city", CITY_KEYWORD),
        ("baldwin park", CITY_KEYWORD),
        ("baldwinsville", CITY_KEYWORD),
        ("bali", CITY_KEYWORD),
        ("balikpapan", CITY_KEYWORD),
        ("ballarat", CITY_KEYWORD),
        ("ballerup", CITY_KEYWORD),
        ("ballina", CITY_KEYWORD),
        ("ballston spa", CITY_KEYWORD),
        ("ballwin", CITY_KEYWORD),
        ("ballymena", CITY_KEYWORD),
        ("balmain", CITY_KEYWORD),
        ("baltic", CITY_KEYWORD),
        ("baltimore", CITY_KEYWORD),
        ("bamako", CITY_KEYWORD),
        ("bamberg", CITY_KEYWORD),
        ("bamenda", CITY_KEYWORD),
        ("banbury", CITY_KEYWORD),
        ("bancroft", CITY_KEYWORD),
        ("banda aceh", CITY_KEYWORD),
        ("bandar baru bangi", CITY_KEYWORD),
        ("bandar lampung", CITY_KEYWORD),
        ("bandar puchong jaya", CITY_KEYWORD),
        ("bandar seri begawan", CITY_KEYWORD),
        ("bandar sunway", CITY_KEYWORD),
        ("bandon", CITY_KEYWORD),
        ("bandung", CITY_KEYWORD),
        ("banff", CITY_KEYWORD),
        ("bangalore", CITY_KEYWORD),
        ("bangi", CITY_KEYWORD),
        ("bangkalan", CITY_KEYWORD),
        ("bangkok", CITY_KEYWORD),
        ("bangor", CITY_KEYWORD),
        ("bangui", CITY_KEYWORD),
        ("banja luka", CITY_KEYWORD),
        ("banjarbaru", CITY_KEYWORD),
        ("banjarmasin", CITY_KEYWORD),
        ("banjul", CITY_KEYWORD),
        ("banks", CITY_KEYWORD),
        ("bankstown", CITY_KEYWORD),
        ("bankura", CITY_KEYWORD),
        ("banning", CITY_KEYWORD),
        ("bannockburn", CITY_KEYWORD),
        ("banska bystrica", CITY_KEYWORD),
        ("banyuls-sur-mer", CITY_KEYWORD),
        ("banyuwangi", CITY_KEYWORD),
        ("baoding", CITY_KEYWORD),
        ("baoji", CITY_KEYWORD),
        ("baoshan", CITY_KEYWORD),
        ("baotou", CITY_KEYWORD),
        ("barabanki", CITY_KEYWORD),
        ("baraboo", CITY_KEYWORD),
        ("baraga", CITY_KEYWORD),
        ("barbacena", CITY_KEYWORD),
        ("barberton", CITY_KEYWORD),
        ("barbourville", CITY_KEYWORD),
        ("barcarena", CITY_KEYWORD),
        ("barcelona", CITY_KEYWORD),
        ("bardstown", CITY_KEYWORD),
        ("bareilly", CITY_KEYWORD),
        ("bar harbor", CITY_KEYWORD),
        ("bari", CITY_KEYWORD),
        ("bariloche", CITY_KEYWORD),
        ("barking", CITY_KEYWORD),
        ("barksdale afb", CITY_KEYWORD),
        ("barnaul", CITY_KEYWORD),
        ("barnesville", CITY_KEYWORD),
        ("barnet", CITY_KEYWORD),
        ("barneveld", CITY_KEYWORD),
        ("barnsley", CITY_KEYWORD),
        ("barnstaple", CITY_KEYWORD),
        ("barnwell", CITY_KEYWORD),
        ("baroda", CITY_KEYWORD),
        ("barpeta", CITY_KEYWORD),
        ("barquisimeto", CITY_KEYWORD),
        ("barranquilla", CITY_KEYWORD),
        ("barre", CITY_KEYWORD),
        ("barretos", CITY_KEYWORD),
        ("barrhead", CITY_KEYWORD),
        ("barrie", CITY_KEYWORD),
        ("barrigada", CITY_KEYWORD),
        ("barrington", CITY_KEYWORD),
        ("barron", CITY_KEYWORD),
        ("barrow", CITY_KEYWORD),
        ("barrow in furness", CITY_KEYWORD),
        ("barrow-in-furness", CITY_KEYWORD),
        ("barry", CITY_KEYWORD),
        ("barstow", CITY_KEYWORD),
        ("bartlesville", CITY_KEYWORD),
        ("bartlett", CITY_KEYWORD),
        ("barton", CITY_KEYWORD),
        ("bartonville", CITY_KEYWORD),
        ("bartow", CITY_KEYWORD),
        ("barueri", CITY_KEYWORD),
        ("basel", CITY_KEYWORD),
        ("basildon", CITY_KEYWORD),
        ("basin", CITY_KEYWORD),
        ("basingstoke", CITY_KEYWORD),
        ("basking ridge", CITY_KEYWORD),
        ("basseterre", CITY_KEYWORD),
        ("bassett", CITY_KEYWORD),
        ("bastrop", CITY_KEYWORD),
        ("batam", CITY_KEYWORD),
        ("batavia", CITY_KEYWORD),
        ("batesville", CITY_KEYWORD),
        ("bath", CITY_KEYWORD),
        ("bathinda", CITY_KEYWORD),
        ("bathurst", CITY_KEYWORD),
        ("batley", CITY_KEYWORD),
        ("batna", CITY_KEYWORD),
        ("baton rouge", CITY_KEYWORD),
        ("battaramulla", CITY_KEYWORD),
        ("battle", CITY_KEYWORD),
        ("battle creek", CITY_KEYWORD),
        ("battle ground", CITY_KEYWORD),
        ("batu caves", CITY_KEYWORD),
        ("batumi", CITY_KEYWORD),
        ("batu pahat", CITY_KEYWORD),
        ("bauchi", CITY_KEYWORD),
        ("baudette", CITY_KEYWORD),
        ("baudour", CITY_KEYWORD),
        ("baulkham hills", CITY_KEYWORD),
        ("baumholder", CITY_KEYWORD),
        ("bauru", CITY_KEYWORD),
        ("baxley", CITY_KEYWORD),
        ("baxter", CITY_KEYWORD),
        ("bayamon", CITY_KEYWORD),
        ("bayan lepas", CITY_KEYWORD),
        ("bayannur", CITY_KEYWORD),
        ("bayboro", CITY_KEYWORD),
        ("bay city", CITY_KEYWORD),
        ("bayfield", CITY_KEYWORD),
        ("bay minette", CITY_KEYWORD),
        ("bayonne", CITY_KEYWORD),
        ("bayport", CITY_KEYWORD),
        ("bayreuth", CITY_KEYWORD),
        ("bay saint louis", CITY_KEYWORD),
        ("bay shore", CITY_KEYWORD),
        ("bayside", CITY_KEYWORD),
        ("bayswater", CITY_KEYWORD),
        ("baytown", CITY_KEYWORD),
        ("bay village", CITY_KEYWORD),
        ("bayville", CITY_KEYWORD),
        ("bazhong", CITY_KEYWORD),
        ("bazhou", CITY_KEYWORD),
        ("beachwood", CITY_KEYWORD),
        ("beacon", CITY_KEYWORD),
        ("beaconsfield", CITY_KEYWORD),
        ("beale afb", CITY_KEYWORD),
        ("beardstown", CITY_KEYWORD),
        ("beatrice", CITY_KEYWORD),
        ("beaucouze", CITY_KEYWORD),
        ("beaudesert", CITY_KEYWORD),
        ("beaufort", CITY_KEYWORD),
        ("beaumont", CITY_KEYWORD),
        ("beausejour", CITY_KEYWORD),
        ("beaver", CITY_KEYWORD),
        ("beavercreek", CITY_KEYWORD),
        ("beaver dam", CITY_KEYWORD),
        ("beaver falls", CITY_KEYWORD),
        ("beaver island", CITY_KEYWORD),
        ("beaverton", CITY_KEYWORD),
        ("bebington", CITY_KEYWORD),
        ("beckenham", CITY_KEYWORD),
        ("becker", CITY_KEYWORD),
        ("beckley", CITY_KEYWORD),
        ("bedford", CITY_KEYWORD),
        ("bedford hills", CITY_KEYWORD),
        ("bedford park", CITY_KEYWORD),
        ("bedfordview", CITY_KEYWORD),
        ("bedminster", CITY_KEYWORD),
        ("beebe", CITY_KEYWORD),
        ("beech grove", CITY_KEYWORD),
        ("beecroft", CITY_KEYWORD),
        ("beed", CITY_KEYWORD),
        ("beenleigh", CITY_KEYWORD),
        ("beerse", CITY_KEYWORD),
        ("beer sheva", CITY_KEYWORD),
        ("beer-sheva", CITY_KEYWORD),
        ("beeville", CITY_KEYWORD),
        ("bega", CITY_KEYWORD),
        ("bei'an", CITY_KEYWORD),
        ("beihai", CITY_KEYWORD),
        ("beijing", CITY_KEYWORD),
        ("beiliu", CITY_KEYWORD),
        ("beipiao", CITY_KEYWORD),
        ("beira", CITY_KEYWORD),
        ("beirut", CITY_KEYWORD),
        ("beitun", CITY_KEYWORD),
        ("beizhen", CITY_KEYWORD),
        ("beja", CITY_KEYWORD),
        ("bejaia", CITY_KEYWORD),
        ("bekasi", CITY_KEYWORD),
        ("bekescsaba", CITY_KEYWORD),
        ("bel air", CITY_KEYWORD),
        ("belchertown", CITY_KEYWORD),
        ("belconnen", CITY_KEYWORD),
        ("belcourt", CITY_KEYWORD),
        ("belding", CITY_KEYWORD),
        ("belem", CITY_KEYWORD),
        ("belém", CITY_KEYWORD),
        ("belfair", CITY_KEYWORD),
        ("belfast", CITY_KEYWORD),
        ("belfry", CITY_KEYWORD),
        ("belgaum", CITY_KEYWORD),
        ("belgrade", CITY_KEYWORD),
        ("belize city", CITY_KEYWORD),
        ("bellaire", CITY_KEYWORD),
        ("bellary", CITY_KEYWORD),
        ("bellaterra", CITY_KEYWORD),
        ("bella vista", CITY_KEYWORD),
        ("bellbrook", CITY_KEYWORD),
        ("belle chasse", CITY_KEYWORD),
        ("bellefontaine", CITY_KEYWORD),
        ("bellefonte", CITY_KEYWORD),
        ("belle fourche", CITY_KEYWORD),
        ("belle glade", CITY_KEYWORD),
        ("belle plaine", CITY_KEYWORD),
        ("bellerose", CITY_KEYWORD),
        ("belle vernon", CITY_KEYWORD),
        ("belleview", CITY_KEYWORD),
        ("belleville", CITY_KEYWORD),
        ("bellevue", CITY_KEYWORD),
        ("bellflower", CITY_KEYWORD),
        ("bellingham", CITY_KEYWORD),
        ("bellinzona", CITY_KEYWORD),
        ("bellmore", CITY_KEYWORD),
        ("bellows falls", CITY_KEYWORD),
        ("bellport", CITY_KEYWORD),
        ("bells", CITY_KEYWORD),
        ("bellshill", CITY_KEYWORD),
        ("bellville", CITY_KEYWORD),
        ("bellwood", CITY_KEYWORD),
        ("belmar", CITY_KEYWORD),
        ("belmond", CITY_KEYWORD),
        ("belmont", CITY_KEYWORD),
        ("belmopan", CITY_KEYWORD),
        ("belo horizonte", CITY_KEYWORD),
        ("beloit", CITY_KEYWORD),
        ("belper", CITY_KEYWORD),
        ("belpre", CITY_KEYWORD),
        ("belrose", CITY_KEYWORD),
        ("belton", CITY_KEYWORD),
        ("beltsville", CITY_KEYWORD),
        ("belvidere", CITY_KEYWORD),
        ("belville", CITY_KEYWORD),
        ("bemidji", CITY_KEYWORD),
        ("benalla", CITY_KEYWORD),
        ("benalmadena", CITY_KEYWORD),
        ("bend", CITY_KEYWORD),
        ("bendigo", CITY_KEYWORD),
        ("benevento", CITY_KEYWORD),
        ("benfleet", CITY_KEYWORD),
        ("bengaluru", CITY_KEYWORD),
        ("bengbu", CITY_KEYWORD),
        ("benghazi", CITY_KEYWORD),
        ("bengkulu", CITY_KEYWORD),
        ("benha", CITY_KEYWORD),
        ("benicia", CITY_KEYWORD),
        ("benin", CITY_KEYWORD),
        ("benin city", CITY_KEYWORD),
        ("beni suef", CITY_KEYWORD),
        ("benito juarez", CITY_KEYWORD),
        ("benito juárez", CITY_KEYWORD),
        ("benmore", CITY_KEYWORD),
        ("bennett", CITY_KEYWORD),
        ("bennettsville", CITY_KEYWORD),
        ("bennington", CITY_KEYWORD),
        ("bensalem", CITY_KEYWORD),
        ("bensenville", CITY_KEYWORD),
        ("bensheim", CITY_KEYWORD),
        ("benson", CITY_KEYWORD),
        ("bentivoglio", CITY_KEYWORD),
        ("bentley", CITY_KEYWORD),
        ("bentleyville", CITY_KEYWORD),
        ("benton", CITY_KEYWORD),
        ("benton city", CITY_KEYWORD),
        ("benton harbor", CITY_KEYWORD),
        ("bentonville", CITY_KEYWORD),
        ("benxi", CITY_KEYWORD),
        ("benzonia", CITY_KEYWORD),
        ("beograd", CITY_KEYWORD),
        ("beppu", CITY_KEYWORD),
        ("berchem", CITY_KEYWORD),
        ("berea", CITY_KEYWORD),
        ("beresford", CITY_KEYWORD),
        ("bergamo", CITY_KEYWORD),
        ("bergen", CITY_KEYWORD),
        ("bergenfield", CITY_KEYWORD),
        ("bergen op zoom", CITY_KEYWORD),
        ("bergisch gladbach", CITY_KEYWORD),
        ("berhampur", CITY_KEYWORD),
        ("berkeley", CITY_KEYWORD),
        ("berkeley heights", CITY_KEYWORD),
        ("berkhamsted", CITY_KEYWORD),
        ("berkley", CITY_KEYWORD),
        ("berlin", CITY_KEYWORD),
        ("bern", CITY_KEYWORD),
        ("bernardsville", CITY_KEYWORD),
        ("bernburg", CITY_KEYWORD),
        ("berne", CITY_KEYWORD),
        ("bernkastel-kues", CITY_KEYWORD),
        ("berri", CITY_KEYWORD),
        ("berrien springs", CITY_KEYWORD),
        ("berrigan", CITY_KEYWORD),
        ("berryville", CITY_KEYWORD),
        ("berthoud", CITY_KEYWORD),
        ("berwick", CITY_KEYWORD),
        ("berwyn", CITY_KEYWORD),
        ("besancon", CITY_KEYWORD),
        ("besançon", CITY_KEYWORD),
        ("beshoftu", CITY_KEYWORD),
        ("bessemer", CITY_KEYWORD),
        ("bethalto", CITY_KEYWORD),
        ("bethany", CITY_KEYWORD),
        ("bethel", CITY_KEYWORD),
        ("bethel park", CITY_KEYWORD),
        ("bethesda", CITY_KEYWORD),
        ("bethlehem", CITY_KEYWORD),
        ("bethpage", CITY_KEYWORD),
        ("bethune", CITY_KEYWORD),
        ("betim", CITY_KEYWORD),
        ("bettendorf", CITY_KEYWORD),
        ("bettsville", CITY_KEYWORD),
        ("beulah", CITY_KEYWORD),
        ("beverley", CITY_KEYWORD),
        ("beverly", CITY_KEYWORD),
        ("beverly hills", CITY_KEYWORD),
        ("bewdley", CITY_KEYWORD),
        ("bexley", CITY_KEYWORD),
        ("bexleyheath", CITY_KEYWORD),
        ("bhagalpur", CITY_KEYWORD),
        ("bhaktapur", CITY_KEYWORD),
        ("bharatpur", CITY_KEYWORD),
        ("bharuch", CITY_KEYWORD),
        ("bhavnagar", CITY_KEYWORD),
        ("bhilai", CITY_KEYWORD),
        ("bhilwara", CITY_KEYWORD),
        ("bhimavaram", CITY_KEYWORD),
        ("bhisho", CITY_KEYWORD),
        ("bhiwani", CITY_KEYWORD),
        ("bhopal", CITY_KEYWORD),
        ("bhubaneshwar", CITY_KEYWORD),
        ("bhubaneswar", CITY_KEYWORD),
        ("bhuj", CITY_KEYWORD),
        ("bhusawal", CITY_KEYWORD),
        ("biak", CITY_KEYWORD),
        ("bialystok", CITY_KEYWORD),
        ("biberach", CITY_KEYWORD),
        ("biberach an der riss", CITY_KEYWORD),
        ("bicester", CITY_KEYWORD),
        ("bicknell", CITY_KEYWORD),
        ("bidar", CITY_KEYWORD),
        ("biddeford", CITY_KEYWORD),
        ("biel", CITY_KEYWORD),
        ("bielefeld", CITY_KEYWORD),
        ("biella", CITY_KEYWORD),
        ("bielsko-biala", CITY_KEYWORD),
        ("bietigheim-bissingen", CITY_KEYWORD),
        ("big bend", CITY_KEYWORD),
        ("bigfork", CITY_KEYWORD),
        ("biggar", CITY_KEYWORD),
        ("biggleswade", CITY_KEYWORD),
        ("big lake", CITY_KEYWORD),
        ("big piney", CITY_KEYWORD),
        ("big rapids", CITY_KEYWORD),
        ("big sandy", CITY_KEYWORD),
        ("big spring", CITY_KEYWORD),
        ("big sur", CITY_KEYWORD),
        ("big timber", CITY_KEYWORD),
        ("bihac", CITY_KEYWORD),
        ("bijapur", CITY_KEYWORD),
        ("bijie", CITY_KEYWORD),
        ("bikaner", CITY_KEYWORD),
        ("bilaspur", CITY_KEYWORD),
        ("bilbao", CITY_KEYWORD),
        ("bilimora", CITY_KEYWORD),
        ("billerica", CITY_KEYWORD),
        ("billericay", CITY_KEYWORD),
        ("billingham", CITY_KEYWORD),
        ("billings", CITY_KEYWORD),
        ("billingshurst", CITY_KEYWORD),
        ("biloela", CITY_KEYWORD),
        ("biloxi", CITY_KEYWORD),
        ("bilthoven", CITY_KEYWORD)))
}