package edu.umass.cs.iesl.watr
package simstring

import heuristics.Constants._

object CountryKeywords {

    final val keywords = FuzzyMap(List(("afghanistan", COUNTRY_KEYWORD),
        ("afg", COUNTRY_KEYWORD),
        ("albania", COUNTRY_KEYWORD),
        ("alb", COUNTRY_KEYWORD),
        ("algeria", COUNTRY_KEYWORD),
        ("dza", COUNTRY_KEYWORD),
        ("american samoa", COUNTRY_KEYWORD),
        ("asm", COUNTRY_KEYWORD),
        ("andorra", COUNTRY_KEYWORD),
        ("angola", COUNTRY_KEYWORD),
        ("ago", COUNTRY_KEYWORD),
        ("anguilla", COUNTRY_KEYWORD),
        ("aia", COUNTRY_KEYWORD),
        ("antarctica", COUNTRY_KEYWORD),
        ("ata", COUNTRY_KEYWORD),
        ("antigua and barbuda", COUNTRY_KEYWORD),
        ("atg", COUNTRY_KEYWORD),
        ("argentina", COUNTRY_KEYWORD),
        ("arg", COUNTRY_KEYWORD),
        ("armenia", COUNTRY_KEYWORD),
        ("arm", COUNTRY_KEYWORD),
        ("aruba", COUNTRY_KEYWORD),
        ("abw", COUNTRY_KEYWORD),
        ("australia", COUNTRY_KEYWORD),
        ("aus", COUNTRY_KEYWORD),
        ("austria", COUNTRY_KEYWORD),
        ("aut", COUNTRY_KEYWORD),
        ("azerbaijan", COUNTRY_KEYWORD),
        ("aze", COUNTRY_KEYWORD),
        ("bahamas", COUNTRY_KEYWORD),
        ("bhs", COUNTRY_KEYWORD),
        ("bahrain", COUNTRY_KEYWORD),
        ("bhr", COUNTRY_KEYWORD),
        ("bangladesh", COUNTRY_KEYWORD),
        ("bgd", COUNTRY_KEYWORD),
        ("barbados", COUNTRY_KEYWORD),
        ("brb", COUNTRY_KEYWORD),
        ("belarus", COUNTRY_KEYWORD),
        ("blr", COUNTRY_KEYWORD),
        ("belgium", COUNTRY_KEYWORD),
        ("bel", COUNTRY_KEYWORD),
        ("belize", COUNTRY_KEYWORD),
        ("blz", COUNTRY_KEYWORD),
        ("benin", COUNTRY_KEYWORD),
        ("ben", COUNTRY_KEYWORD),
        ("bermuda", COUNTRY_KEYWORD),
        ("bmu", COUNTRY_KEYWORD),
        ("bhutan", COUNTRY_KEYWORD),
        ("btn", COUNTRY_KEYWORD),
        ("bolivia", COUNTRY_KEYWORD),
        ("bol", COUNTRY_KEYWORD),
        ("bonaire", COUNTRY_KEYWORD),
        ("bes", COUNTRY_KEYWORD),
        ("bosnia and herzegovina", COUNTRY_KEYWORD),
        ("bih", COUNTRY_KEYWORD),
        ("botswana", COUNTRY_KEYWORD),
        ("bwa", COUNTRY_KEYWORD),
        ("bouvet island", COUNTRY_KEYWORD),
        ("bvt", COUNTRY_KEYWORD),
        ("brazil", COUNTRY_KEYWORD),
        ("bra", COUNTRY_KEYWORD),
        ("british indian ocean territory", COUNTRY_KEYWORD),
        ("iot", COUNTRY_KEYWORD),
        ("brunei darussalam", COUNTRY_KEYWORD),
        ("brn", COUNTRY_KEYWORD),
        ("bulgaria", COUNTRY_KEYWORD),
        ("bgr", COUNTRY_KEYWORD),
        ("burkina faso", COUNTRY_KEYWORD),
        ("bfa", COUNTRY_KEYWORD),
        ("burundi", COUNTRY_KEYWORD),
        ("bdi", COUNTRY_KEYWORD),
        ("cambodia", COUNTRY_KEYWORD),
        ("khm", COUNTRY_KEYWORD),
        ("cameroon", COUNTRY_KEYWORD),
        ("cmr", COUNTRY_KEYWORD),
        ("canada", COUNTRY_KEYWORD),
        ("can", COUNTRY_KEYWORD),
        ("cape verde", COUNTRY_KEYWORD),
        ("cpv", COUNTRY_KEYWORD),
        ("cayman islands", COUNTRY_KEYWORD),
        ("cym", COUNTRY_KEYWORD),
        ("central african republic", COUNTRY_KEYWORD),
        ("caf", COUNTRY_KEYWORD),
        ("chad", COUNTRY_KEYWORD),
        ("tcd", COUNTRY_KEYWORD),
        ("chile", COUNTRY_KEYWORD),
        ("chl", COUNTRY_KEYWORD),
        ("china", COUNTRY_KEYWORD),
        ("chn", COUNTRY_KEYWORD),
        ("christmas island", COUNTRY_KEYWORD),
        ("cxr", COUNTRY_KEYWORD),
        ("cocos islands", COUNTRY_KEYWORD),
        ("cck", COUNTRY_KEYWORD),
        ("colombia", COUNTRY_KEYWORD),
        ("col", COUNTRY_KEYWORD),
        ("comoros", COUNTRY_KEYWORD),
        ("com", COUNTRY_KEYWORD),
        ("congo", COUNTRY_KEYWORD),
        ("cog", COUNTRY_KEYWORD),
        ("congo, the democratic republic of the", COUNTRY_KEYWORD),
        ("cod", COUNTRY_KEYWORD),
        ("cook islands", COUNTRY_KEYWORD),
        ("cok", COUNTRY_KEYWORD),
        ("costa rica", COUNTRY_KEYWORD),
        ("cri", COUNTRY_KEYWORD),
        ("croatia", COUNTRY_KEYWORD),
        ("hrv", COUNTRY_KEYWORD),
        ("cuba", COUNTRY_KEYWORD),
        ("cub", COUNTRY_KEYWORD),
        ("cyprus", COUNTRY_KEYWORD),
        ("cyp", COUNTRY_KEYWORD),
        ("czech republic", COUNTRY_KEYWORD),
        ("cze", COUNTRY_KEYWORD),
        ("denmark", COUNTRY_KEYWORD),
        ("dnk", COUNTRY_KEYWORD),
        ("djibouti", COUNTRY_KEYWORD),
        ("dji", COUNTRY_KEYWORD),
        ("dominica", COUNTRY_KEYWORD),
        ("dma", COUNTRY_KEYWORD),
        ("dominican republic", COUNTRY_KEYWORD),
        ("dominican", COUNTRY_KEYWORD),
        ("dom", COUNTRY_KEYWORD),
        ("ecuador", COUNTRY_KEYWORD),
        ("ecu", COUNTRY_KEYWORD),
        ("egypt", COUNTRY_KEYWORD),
        ("egy", COUNTRY_KEYWORD),
        ("el salvador", COUNTRY_KEYWORD),
        ("slv", COUNTRY_KEYWORD),
        ("equatorial guinea", COUNTRY_KEYWORD),
        ("gnq", COUNTRY_KEYWORD),
        ("eritrea", COUNTRY_KEYWORD),
        ("eri", COUNTRY_KEYWORD),
        ("estonia", COUNTRY_KEYWORD),
        ("est", COUNTRY_KEYWORD),
        ("ethiopia", COUNTRY_KEYWORD),
        ("eth", COUNTRY_KEYWORD),
        ("falkland islands ", COUNTRY_KEYWORD),
        ("flk", COUNTRY_KEYWORD),
        ("faroe islands", COUNTRY_KEYWORD),
        ("fro", COUNTRY_KEYWORD),
        ("fiji", COUNTRY_KEYWORD),
        ("fji", COUNTRY_KEYWORD),
        ("finland", COUNTRY_KEYWORD),
        ("fin", COUNTRY_KEYWORD),
        ("france", COUNTRY_KEYWORD),
        ("fra", COUNTRY_KEYWORD),
        ("french guiana", COUNTRY_KEYWORD),
        ("guf", COUNTRY_KEYWORD),
        ("french polynesia", COUNTRY_KEYWORD),
        ("pyf", COUNTRY_KEYWORD),
        ("french southern territories", COUNTRY_KEYWORD),
        ("atf", COUNTRY_KEYWORD),
        ("gabon", COUNTRY_KEYWORD),
        ("gab", COUNTRY_KEYWORD),
        ("gambia", COUNTRY_KEYWORD),
        ("gmb", COUNTRY_KEYWORD),
        ("georgia", COUNTRY_KEYWORD),
        ("geo", COUNTRY_KEYWORD),
        ("germany", COUNTRY_KEYWORD),
        ("great britain", COUNTRY_KEYWORD),
        ("deu", COUNTRY_KEYWORD),
        ("ghana", COUNTRY_KEYWORD),
        ("gha", COUNTRY_KEYWORD),
        ("gibraltar", COUNTRY_KEYWORD),
        ("gib", COUNTRY_KEYWORD),
        ("greece", COUNTRY_KEYWORD),
        ("grc", COUNTRY_KEYWORD),
        ("greenland", COUNTRY_KEYWORD),
        ("grl", COUNTRY_KEYWORD),
        ("grenada", COUNTRY_KEYWORD),
        ("grd", COUNTRY_KEYWORD),
        ("guadeloupe", COUNTRY_KEYWORD),
        ("glp", COUNTRY_KEYWORD),
        ("guam", COUNTRY_KEYWORD),
        ("gum", COUNTRY_KEYWORD),
        ("guatemala", COUNTRY_KEYWORD),
        ("gtm", COUNTRY_KEYWORD),
        ("guernsey", COUNTRY_KEYWORD),
        ("ggy", COUNTRY_KEYWORD),
        ("guinea", COUNTRY_KEYWORD),
        ("gin", COUNTRY_KEYWORD),
        ("guinea-bissau", COUNTRY_KEYWORD),
        ("gnb", COUNTRY_KEYWORD),
        ("guyana", COUNTRY_KEYWORD),
        ("guy", COUNTRY_KEYWORD),
        ("haiti", COUNTRY_KEYWORD),
        ("hti", COUNTRY_KEYWORD),
        ("heard island and mcdonald islands", COUNTRY_KEYWORD),
        ("hmd", COUNTRY_KEYWORD),
        ("holy see ", COUNTRY_KEYWORD),
        ("vat", COUNTRY_KEYWORD),
        ("honduras", COUNTRY_KEYWORD),
        ("hnd", COUNTRY_KEYWORD),
        ("hong kong", COUNTRY_KEYWORD),
        ("hkg", COUNTRY_KEYWORD),
        ("hungary", COUNTRY_KEYWORD),
        ("hun", COUNTRY_KEYWORD),
        ("iceland", COUNTRY_KEYWORD),
        ("isl", COUNTRY_KEYWORD),
        ("india", COUNTRY_KEYWORD),
        ("ind", COUNTRY_KEYWORD),
        ("indonesia", COUNTRY_KEYWORD),
        ("idn", COUNTRY_KEYWORD),
        ("iran", COUNTRY_KEYWORD),
        ("irn", COUNTRY_KEYWORD),
        ("iraq", COUNTRY_KEYWORD),
        ("irq", COUNTRY_KEYWORD),
        ("ireland", COUNTRY_KEYWORD),
        ("irl", COUNTRY_KEYWORD),
        ("isle of man", COUNTRY_KEYWORD),
        ("imn", COUNTRY_KEYWORD),
        ("israel", COUNTRY_KEYWORD),
        ("isr", COUNTRY_KEYWORD),
        ("italy", COUNTRY_KEYWORD),
        ("ita", COUNTRY_KEYWORD),
        ("jamaica", COUNTRY_KEYWORD),
        ("jam", COUNTRY_KEYWORD),
        ("japan", COUNTRY_KEYWORD),
        ("jpn", COUNTRY_KEYWORD),
        ("jersey", COUNTRY_KEYWORD),
        ("jey", COUNTRY_KEYWORD),
        ("jordan", COUNTRY_KEYWORD),
        ("jor", COUNTRY_KEYWORD),
        ("kazakhstan", COUNTRY_KEYWORD),
        ("kaz", COUNTRY_KEYWORD),
        ("kenya", COUNTRY_KEYWORD),
        ("ken", COUNTRY_KEYWORD),
        ("kiribati", COUNTRY_KEYWORD),
        ("kir", COUNTRY_KEYWORD),
        ("korea", COUNTRY_KEYWORD),
        ("prk", COUNTRY_KEYWORD),
        ("korea, republic of", COUNTRY_KEYWORD),
        ("kor", COUNTRY_KEYWORD),
        ("kuwait", COUNTRY_KEYWORD),
        ("kwt", COUNTRY_KEYWORD),
        ("kyrgyzstan", COUNTRY_KEYWORD),
        ("kgz", COUNTRY_KEYWORD),
        ("lao people's democratic republic", COUNTRY_KEYWORD),
        ("lao", COUNTRY_KEYWORD),
        ("latvia", COUNTRY_KEYWORD),
        ("lva", COUNTRY_KEYWORD),
        ("lebanon", COUNTRY_KEYWORD),
        ("lbn", COUNTRY_KEYWORD),
        ("lesotho", COUNTRY_KEYWORD),
        ("lso", COUNTRY_KEYWORD),
        ("liberia", COUNTRY_KEYWORD),
        ("lbr", COUNTRY_KEYWORD),
        ("libya", COUNTRY_KEYWORD),
        ("lby", COUNTRY_KEYWORD),
        ("liechtenstein", COUNTRY_KEYWORD),
        ("lie", COUNTRY_KEYWORD),
        ("lithuania", COUNTRY_KEYWORD),
        ("ltu", COUNTRY_KEYWORD),
        ("luxembourg", COUNTRY_KEYWORD),
        ("lux", COUNTRY_KEYWORD),
        ("macao", COUNTRY_KEYWORD),
        ("mac", COUNTRY_KEYWORD),
        ("macedonia, republic of", COUNTRY_KEYWORD),
        ("macedonia", COUNTRY_KEYWORD),
        ("mkd", COUNTRY_KEYWORD),
        ("madagascar", COUNTRY_KEYWORD),
        ("mdg", COUNTRY_KEYWORD),
        ("malawi", COUNTRY_KEYWORD),
        ("mwi", COUNTRY_KEYWORD),
        ("malaysia", COUNTRY_KEYWORD),
        ("scotland", COUNTRY_KEYWORD),
        ("wales", COUNTRY_KEYWORD),
        ("mys", COUNTRY_KEYWORD),
        ("maldives", COUNTRY_KEYWORD),
        ("mdv", COUNTRY_KEYWORD),
        ("mali", COUNTRY_KEYWORD),
        ("mli", COUNTRY_KEYWORD),
        ("malta", COUNTRY_KEYWORD),
        ("mlt", COUNTRY_KEYWORD),
        ("marshall islands", COUNTRY_KEYWORD),
        ("mhl", COUNTRY_KEYWORD),
        ("martinique", COUNTRY_KEYWORD),
        ("mtq", COUNTRY_KEYWORD),
        ("mauritania", COUNTRY_KEYWORD),
        ("mrt", COUNTRY_KEYWORD),
        ("mauritius", COUNTRY_KEYWORD),
        ("mus", COUNTRY_KEYWORD),
        ("mayotte", COUNTRY_KEYWORD),
        ("myt", COUNTRY_KEYWORD),
        ("mexico", COUNTRY_KEYWORD),
        ("mex", COUNTRY_KEYWORD),
        ("micronesia, federated states of", COUNTRY_KEYWORD),
        ("micronesia", COUNTRY_KEYWORD),
        ("fsm", COUNTRY_KEYWORD),
        ("moldova, republic of", COUNTRY_KEYWORD),
        ("mda", COUNTRY_KEYWORD),
        ("monaco", COUNTRY_KEYWORD),
        ("mco", COUNTRY_KEYWORD),
        ("mongolia", COUNTRY_KEYWORD),
        ("mng", COUNTRY_KEYWORD),
        ("montenegro", COUNTRY_KEYWORD),
        ("mne", COUNTRY_KEYWORD),
        ("montserrat", COUNTRY_KEYWORD),
        ("msr", COUNTRY_KEYWORD),
        ("morocco", COUNTRY_KEYWORD),
        ("mar", COUNTRY_KEYWORD),
        ("mozambique", COUNTRY_KEYWORD),
        ("moz", COUNTRY_KEYWORD),
        ("myanmar", COUNTRY_KEYWORD),
        ("mmr", COUNTRY_KEYWORD),
        ("namibia", COUNTRY_KEYWORD),
        ("nam", COUNTRY_KEYWORD),
        ("nauru", COUNTRY_KEYWORD),
        ("nru", COUNTRY_KEYWORD),
        ("nepal", COUNTRY_KEYWORD),
        ("npl", COUNTRY_KEYWORD),
        ("netherlands", COUNTRY_KEYWORD),
        ("nld", COUNTRY_KEYWORD),
        ("new caledonia", COUNTRY_KEYWORD),
        ("ncl", COUNTRY_KEYWORD),
        ("new zealand", COUNTRY_KEYWORD),
        ("nzl", COUNTRY_KEYWORD),
        ("nicaragua", COUNTRY_KEYWORD),
        ("nic", COUNTRY_KEYWORD),
        ("niger", COUNTRY_KEYWORD),
        ("ner", COUNTRY_KEYWORD),
        ("nigeria", COUNTRY_KEYWORD),
        ("nga", COUNTRY_KEYWORD),
        ("niue", COUNTRY_KEYWORD),
        ("niu", COUNTRY_KEYWORD),
        ("norfolk island", COUNTRY_KEYWORD),
        ("nfk", COUNTRY_KEYWORD),
        ("northern mariana islands", COUNTRY_KEYWORD),
        ("mnp", COUNTRY_KEYWORD),
        ("norway", COUNTRY_KEYWORD),
        ("nor", COUNTRY_KEYWORD),
        ("oman", COUNTRY_KEYWORD),
        ("omn", COUNTRY_KEYWORD),
        ("pakistan", COUNTRY_KEYWORD),
        ("pak", COUNTRY_KEYWORD),
        ("palau", COUNTRY_KEYWORD),
        ("plw", COUNTRY_KEYWORD),
        ("palestine, state of", COUNTRY_KEYWORD),
        ("pse", COUNTRY_KEYWORD),
        ("panama", COUNTRY_KEYWORD),
        ("pan", COUNTRY_KEYWORD),
        ("papua new guinea", COUNTRY_KEYWORD),
        ("png", COUNTRY_KEYWORD),
        ("paraguay", COUNTRY_KEYWORD),
        ("pry", COUNTRY_KEYWORD),
        ("peru", COUNTRY_KEYWORD),
        ("per", COUNTRY_KEYWORD),
        ("philippines", COUNTRY_KEYWORD),
        ("phl", COUNTRY_KEYWORD),
        ("pitcairn", COUNTRY_KEYWORD),
        ("pcn", COUNTRY_KEYWORD),
        ("poland", COUNTRY_KEYWORD),
        ("pol", COUNTRY_KEYWORD),
        ("portugal", COUNTRY_KEYWORD),
        ("prt", COUNTRY_KEYWORD),
        ("puerto rico", COUNTRY_KEYWORD),
        ("pri", COUNTRY_KEYWORD),
        ("qatar", COUNTRY_KEYWORD),
        ("qat", COUNTRY_KEYWORD),
        ("romania", COUNTRY_KEYWORD),
        ("rou", COUNTRY_KEYWORD),
        ("russian federation", COUNTRY_KEYWORD),
        ("russia", COUNTRY_KEYWORD),
        ("rus", COUNTRY_KEYWORD),
        ("rwanda", COUNTRY_KEYWORD),
        ("rwa", COUNTRY_KEYWORD),
        ("saint helena, ascension and tristan da cunha", COUNTRY_KEYWORD),
        ("shn", COUNTRY_KEYWORD),
        ("saint kitts and nevis", COUNTRY_KEYWORD),
        ("kna", COUNTRY_KEYWORD),
        ("saint lucia", COUNTRY_KEYWORD),
        ("lca", COUNTRY_KEYWORD),
        ("saint martin ", COUNTRY_KEYWORD),
        ("maf", COUNTRY_KEYWORD),
        ("saint pierre and miquelon", COUNTRY_KEYWORD),
        ("spm", COUNTRY_KEYWORD),
        ("saint vincent and the grenadines", COUNTRY_KEYWORD),
        ("vct", COUNTRY_KEYWORD),
        ("samoa", COUNTRY_KEYWORD),
        ("wsm", COUNTRY_KEYWORD),
        ("san marino", COUNTRY_KEYWORD),
        ("smr", COUNTRY_KEYWORD),
        ("sao tome and principe", COUNTRY_KEYWORD),
        ("stp", COUNTRY_KEYWORD),
        ("saudi arabia", COUNTRY_KEYWORD),
        ("sau", COUNTRY_KEYWORD),
        ("senegal", COUNTRY_KEYWORD),
        ("sen", COUNTRY_KEYWORD),
        ("serbia", COUNTRY_KEYWORD),
        ("srb", COUNTRY_KEYWORD),
        ("seychelles", COUNTRY_KEYWORD),
        ("syc", COUNTRY_KEYWORD),
        ("sierra leone", COUNTRY_KEYWORD),
        ("sle", COUNTRY_KEYWORD),
        ("singapore", COUNTRY_KEYWORD),
        ("sgp", COUNTRY_KEYWORD),
        ("sint maarten", COUNTRY_KEYWORD),
        ("sxm", COUNTRY_KEYWORD),
        ("slovakia", COUNTRY_KEYWORD),
        ("espana", COUNTRY_KEYWORD),
        ("svk", COUNTRY_KEYWORD),
        ("slovenia", COUNTRY_KEYWORD),
        ("svn", COUNTRY_KEYWORD),
        ("solomon islands", COUNTRY_KEYWORD),
        ("slb", COUNTRY_KEYWORD),
        ("somalia", COUNTRY_KEYWORD),
        ("som", COUNTRY_KEYWORD),
        ("south africa", COUNTRY_KEYWORD),
        ("zaf", COUNTRY_KEYWORD),
        ("south georgia and the south sandwich islands", COUNTRY_KEYWORD),
        ("sgs", COUNTRY_KEYWORD),
        ("spain", COUNTRY_KEYWORD),
        ("esp", COUNTRY_KEYWORD),
        ("sri lanka", COUNTRY_KEYWORD),
        ("lka", COUNTRY_KEYWORD),
        ("sudan", COUNTRY_KEYWORD),
        ("sdn", COUNTRY_KEYWORD),
        ("suriname", COUNTRY_KEYWORD),
        ("sur", COUNTRY_KEYWORD),
        ("south sudan", COUNTRY_KEYWORD),
        ("south korea", COUNTRY_KEYWORD),
        ("ssd", COUNTRY_KEYWORD),
        ("svalbard and jan mayen", COUNTRY_KEYWORD),
        ("sjm", COUNTRY_KEYWORD),
        ("swaziland", COUNTRY_KEYWORD),
        ("swz", COUNTRY_KEYWORD),
        ("sweden", COUNTRY_KEYWORD),
        ("swe", COUNTRY_KEYWORD),
        ("switzerland", COUNTRY_KEYWORD),
        ("che", COUNTRY_KEYWORD),
        ("syrian arab republic", COUNTRY_KEYWORD),
        ("syria", COUNTRY_KEYWORD),
        ("syr", COUNTRY_KEYWORD),
        ("taiwan, province of china", COUNTRY_KEYWORD),
        ("taiwan", COUNTRY_KEYWORD),
        ("twn", COUNTRY_KEYWORD),
        ("tajikistan", COUNTRY_KEYWORD),
        ("tjk", COUNTRY_KEYWORD),
        ("tanzania, united republic of", COUNTRY_KEYWORD),
        ("tanzania", COUNTRY_KEYWORD),
        ("tza", COUNTRY_KEYWORD),
        ("thailand", COUNTRY_KEYWORD),
        ("tha", COUNTRY_KEYWORD),
        ("timor-leste", COUNTRY_KEYWORD),
        ("tls", COUNTRY_KEYWORD),
        ("togo", COUNTRY_KEYWORD),
        ("tgo", COUNTRY_KEYWORD),
        ("tokelau", COUNTRY_KEYWORD),
        ("tkl", COUNTRY_KEYWORD),
        ("tonga", COUNTRY_KEYWORD),
        ("ton", COUNTRY_KEYWORD),
        ("trinidad and tobago", COUNTRY_KEYWORD),
        ("tto", COUNTRY_KEYWORD),
        ("tunisia", COUNTRY_KEYWORD),
        ("tun", COUNTRY_KEYWORD),
        ("turkey", COUNTRY_KEYWORD),
        ("tur", COUNTRY_KEYWORD),
        ("turkmenistan", COUNTRY_KEYWORD),
        ("tkm", COUNTRY_KEYWORD),
        ("turks and caicos islands", COUNTRY_KEYWORD),
        ("tca", COUNTRY_KEYWORD),
        ("tuvalu", COUNTRY_KEYWORD),
        ("tuv", COUNTRY_KEYWORD),
        ("uganda", COUNTRY_KEYWORD),
        ("uga", COUNTRY_KEYWORD),
        ("ukraine", COUNTRY_KEYWORD),
        ("ukr", COUNTRY_KEYWORD),
        ("united arab emirates", COUNTRY_KEYWORD),
        ("are", COUNTRY_KEYWORD),
        ("united kingdom", COUNTRY_KEYWORD),
        ("gbr", COUNTRY_KEYWORD),
        ("uk", COUNTRY_KEYWORD),
        ("united states", COUNTRY_KEYWORD),
        ("united states of america", COUNTRY_KEYWORD),
        ("usa", COUNTRY_KEYWORD),
        ("us", COUNTRY_KEYWORD),
        ("united states minor outlying islands", COUNTRY_KEYWORD),
        ("umi", COUNTRY_KEYWORD),
        ("uruguay", COUNTRY_KEYWORD),
        ("ury", COUNTRY_KEYWORD),
        ("uzbekistan", COUNTRY_KEYWORD),
        ("uzb", COUNTRY_KEYWORD),
        ("vanuatu", COUNTRY_KEYWORD),
        ("vut", COUNTRY_KEYWORD),
        ("venezuela, bolivarian republic of", COUNTRY_KEYWORD),
        ("venezuela", COUNTRY_KEYWORD),
        ("ven", COUNTRY_KEYWORD),
        ("viet nam", COUNTRY_KEYWORD),
        ("vnm", COUNTRY_KEYWORD),
        ("virgin islands, british", COUNTRY_KEYWORD),
        ("vgb", COUNTRY_KEYWORD),
        ("virgin islands, u.s.", COUNTRY_KEYWORD),
        ("vir", COUNTRY_KEYWORD),
        ("wallis and futuna", COUNTRY_KEYWORD),
        ("wlf", COUNTRY_KEYWORD),
        ("western sahara", COUNTRY_KEYWORD),
        ("esh", COUNTRY_KEYWORD),
        ("yemen", COUNTRY_KEYWORD),
        ("yem", COUNTRY_KEYWORD),
        ("zambia", COUNTRY_KEYWORD),
        ("zmb", COUNTRY_KEYWORD),
        ("zimbabwe", COUNTRY_KEYWORD),
        ("zwe", COUNTRY_KEYWORD),
        ("british antarctic territory", COUNTRY_KEYWORD),
        ("atb", COUNTRY_KEYWORD),
        ("burma, socialist republic of the union of", COUNTRY_KEYWORD),
        ("bur", COUNTRY_KEYWORD),
        ("byelorussian ssr soviet socialist republic", COUNTRY_KEYWORD),
        ("bys", COUNTRY_KEYWORD),
        ("canton and enderbury islands", COUNTRY_KEYWORD),
        ("cte", COUNTRY_KEYWORD),
        ("czechoslovakia, czechoslovak socialist republic", COUNTRY_KEYWORD),
        ("csk", COUNTRY_KEYWORD),
        ("dahomey", COUNTRY_KEYWORD),
        ("dhy", COUNTRY_KEYWORD),
        ("dronning maud land", COUNTRY_KEYWORD),
        ("atn", COUNTRY_KEYWORD),
        ("east timor", COUNTRY_KEYWORD),
        ("tmp", COUNTRY_KEYWORD),
        ("ethiopia", COUNTRY_KEYWORD),
        ("eth", COUNTRY_KEYWORD),
        ("france, metropolitan", COUNTRY_KEYWORD),
        ("fxx", COUNTRY_KEYWORD),
        ("french afars and issas", COUNTRY_KEYWORD),
        ("afi", COUNTRY_KEYWORD),
        ("french southern and antarctic territories", COUNTRY_KEYWORD),
        ("atf", COUNTRY_KEYWORD),
        ("german democratic republic", COUNTRY_KEYWORD),
        ("ddr", COUNTRY_KEYWORD),
        ("germany, federal republic of", COUNTRY_KEYWORD),
        ("deutschland", COUNTRY_KEYWORD),
        ("deu", COUNTRY_KEYWORD),
        ("gilbert and ellice islands", COUNTRY_KEYWORD),
        ("gel", COUNTRY_KEYWORD),
        ("johnston island", COUNTRY_KEYWORD),
        ("jtn", COUNTRY_KEYWORD),
        ("midway islands", COUNTRY_KEYWORD),
        ("mid", COUNTRY_KEYWORD),
        ("netherlands antilles", COUNTRY_KEYWORD),
        ("ant", COUNTRY_KEYWORD),
        ("neutral zone", COUNTRY_KEYWORD),
        ("ntz", COUNTRY_KEYWORD),
        ("new hebrides", COUNTRY_KEYWORD),
        ("nhb", COUNTRY_KEYWORD),
        ("pacific islands ", COUNTRY_KEYWORD),
        ("pci", COUNTRY_KEYWORD),
        ("panama, republic of", COUNTRY_KEYWORD),
        ("pan", COUNTRY_KEYWORD),
        ("panama canal zone", COUNTRY_KEYWORD),
        ("pcz", COUNTRY_KEYWORD),
        ("romania, socialist republic of", COUNTRY_KEYWORD),
        ("romania", COUNTRY_KEYWORD),
        ("rom", COUNTRY_KEYWORD),
        ("st. kitts-nevis-anguilla", COUNTRY_KEYWORD),
        ("kna", COUNTRY_KEYWORD),
        ("serbia and montenegro", COUNTRY_KEYWORD),
        ("scg", COUNTRY_KEYWORD),
        ("sikkim", COUNTRY_KEYWORD),
        ("skm", COUNTRY_KEYWORD),
        ("southern rhodesia", COUNTRY_KEYWORD),
        ("rho", COUNTRY_KEYWORD),
        ("spanish sahara", COUNTRY_KEYWORD),
        ("esh", COUNTRY_KEYWORD),
        ("us miscellaneous pacific islands", COUNTRY_KEYWORD),
        ("pus", COUNTRY_KEYWORD),
        ("ussr, union of soviet socialist republics", COUNTRY_KEYWORD),
        ("sun", COUNTRY_KEYWORD),
        ("upper volta, republic of", COUNTRY_KEYWORD),
        ("hvo", COUNTRY_KEYWORD),
        ("vatican city state (holy see)", COUNTRY_KEYWORD),
        ("vatican", COUNTRY_KEYWORD),
        ("vat", COUNTRY_KEYWORD),
        ("viet-nam, democratic republic of", COUNTRY_KEYWORD),
        ("vdr", COUNTRY_KEYWORD),
        ("wake island", COUNTRY_KEYWORD),
        ("wak", COUNTRY_KEYWORD),
        ("yemen, democratic, people's democratic republic of", COUNTRY_KEYWORD),
        ("yemen", COUNTRY_KEYWORD),
        ("ymd", COUNTRY_KEYWORD),
        ("yemen, yemen arab republic", COUNTRY_KEYWORD),
        ("yem", COUNTRY_KEYWORD),
        ("yugoslavia, socialist federal republic of", COUNTRY_KEYWORD),
        ("yugoslavia", COUNTRY_KEYWORD),
        ("yug", COUNTRY_KEYWORD),
        ("zaire, republic of", COUNTRY_KEYWORD),
        ("zar", COUNTRY_KEYWORD),
        ("republic of macedonia", COUNTRY_KEYWORD)))


}
